class Constants:
    # zoznam pouzitych kostant
    OTHER_OPTION = "Vyber nezodpoveda moznostiam! Skuste este raz!"
    CAGE_NON_EXIST = "Klietka nie je medzi uvazovanymi alebo neexistuje"
    NO_CAGE = "Klietka neexistuje"
    EXOOS_CAGE_PREFIX = "ExoosCages/Cage_"
    TEXT_FILE = ".txt"
    CAGE_64 = "Cage (6,4)"
    
    DETAIL = "detail"
    INCIDENCE_MATRIX = "Incidencna matica klietky, Kontrolna matica H:"
    MOORE_BOUND = "Moorove ohranicenie pre klietku M = "
    N_VERTICES = "Počet vrcholov klietky |ver| = "
    SIZE_H =  "Rozmer kontrolnej matice H = "
    N_EDGES = "Počet hran klietky |edg| = "
    AUTGROUP =  "Počet automorfizmov z klietky |autGroup| = "
    RATE =  "Informačný pomer R = "
    H_DIR_PREFIX = 'ParityCheckMatrices/H_Cage_'
    H_FILE_PREFIX = "Súbor H_Cage"
    SUCCESS_CREATE ='bol uspesne vytvoreny! Doba trvania: '
    CLEAR = 'clear'
    NO_SHOWABLE = "Zoznam graficky nezobrazitelnych klietok"
    SHOWABLE = "Zoznam graficky zobrazitelnych klietok"
    TESIS = "Grupy automorfizmov linearnych kodov"
    SHOWABLE_CATEGORY = "Klietky/Rekordne grafy, ktore graficky vieme zobrazit"
    NO_SHOWABLE_CATEGORY = "Klietky/Rekordne grafy, ktore je graficky narocne zobrazit"
    QUIT = "Koniec"
    BYE = "Dovidenia!"
    AUTGROUP_C = "Zobraz pocet automorfizmov v linearnom kode"  
    C_VALID = 'Linearny kod je validny' 
    C_INVALID = 'Linearny kod nie je validny' 
    G_DIR_PREFIX = 'GeneratorMatrices/G_Cage_'
    G_FILE_PREFIX = 'Súbor G_Cage('
    AUT_GROUP = 'Grupa automorfizmov'
    AUT_GROUP_CAGE_DIR_PREFIX = 'AutomorphismGroups/AutGroup_Cage_'
    AUT_GROUP_FILE_PREFIX = 'Súbor AutGroup_Cage'
    AUT_GROUP_SUFFIX = "_LINEARCODE"

    CAGE = "Cage"
    REC = "Rec"
    MENU = "MENU"
    MAIN = "MAIN"
    BACK_TO = "Naspat na"
    CHOOSE_FROM_OPTIONS = "Vyberte z moznosti:"
    LINEAR_CODE = "LINEARNY KOD"
    GENERATOR_MATRIX = "Generujuca matica G:"
    GENERATOR_MATRIX_DIRECTORY = "GeneratorMatrices"
    GENERATOR_MATRIX_DIM = "Rozmer generujucej matice G:"
    MIN_CODE_DISTANCE = "Minimalna Hammingova vzdialenost v kode d:"
    CODE_LENGTH = "Dlzka linearneho kodu n:"
    NUM_CODE_WORDS = "Pocet kodovych slov m:"
    PERFECT_CODE_PARAMETER = "Parameter perfektneho kodu p:"
    DETAIL = "DETAIL"

    SHOW_G ="Zobraz generujucu maticu G"
    SAVE_G = "Uloz generujucu maticu G"
    SHOW_DIM_G = "Zobraz rozmer generujucej matice G"
    SHOW_AUTGROUP_C = "Zobraz grupu automorfizmov AutGroup(C)"
    SAVE_AUTGROUP_C = "Uloz grupu automorfizmov AutGroup(C)"
    SHOW_N_M = "Zobraz dlzku kodu n a pocet slov m"
    SHOW_D = "Zraz minimalnu Hammingovu vzdialenost d"
    SHOW_P = "Zobraz parameter perfektneho kodu p(n,m,d)"
    LEFT_BORDER = "****        "
    RIGHT_BORDER_BIG = "        ****"
    RIGHT_BORDER_SMALL = "       ****"

    SHOW_H = "Zobraz kontrolnu maticu H"
    SAVE_H ="Uloz kontrolnu maticu H"
    SHOW_DATA = "Zobraz udaje (M, |ver|, rozmer H, |edg|, R)"
    SHOW_AUTGROUP_CAGE = "Zobraz grupu automorfizmov AutGroup(Cage)"
    SAVE_AUTGROUP_CAGE = "Ulož grupu automorfizmov AutGroup(Cage)"
    SHOW_AUTGROUP_REC = "Zobraz grupu automorfizmov AutGroup(Rec)"
    SAVE_AUTGROUP_REC = "Uloz grupu automorfizmov AutGroup(Rec)"
    SHOW_CODE = "Zobraz linearny kod C"
    SHOW_GRAPH = "Zobraz graf"

    PARITY_CHECK_MATRIX = "Kontrolna matica (Incidencna) H:"
    PARITY_CHECK_MATRIX_DIRECTORY = "ParityCheckMatrices"
    AUTOMORPHISM_GROUP_DIRECTORY = "AutomorphismGroups"

    AUTOMORPHISM_GROUP = "GRUPA AUTOMORFIZMOV"
    AUTOMORPHISM = "Automorfizmus"

    N_AUTOMORPHISM_FROM = "Pocet automorfizmov z"
    CHOOSE_AUTOMORPHISM = "Vyberte automorfizmus z ktoreho chcete vygenerovat linearny kod a zobrazit detail:"

    FROM_CODE = "linearneho kódu:"
    NTH_AUTOMORPHISM = ". automorfizmus"

    OPTION_1 = "1"
    OPTION_2 = "2"
    OPTION_3 = "3"
    OPTION_4 = "4"
    OPTION_5 = "5"
    OPTION_6 = "6"
    OPTION_7 = "7"
    OPTION_8 = "8"
    OPTION_9 = "9"
    OPTION_10 = "10"
    OPTION_11 = "11"
    OPTION_12 = "12"
    OPTION_13 = "13"
    OPTION_14 = "14"
    OPTION_15 = "15"
    OPTION_16 = "16"
    OPTION_17 = "17"
    OPTION_18 = "18"
    OPTION_19 = "19"
    OPTION_20 = "20"
    OPTION_21 = "21"
    OPTION_22 = "22"
    OPTION_23 = "23"
    OPTION_24 = "24"
    OPTION_25 = "25"
    OPTION_26 = "26"
    OPTION_Q = "q"
    OPTION_X = "x"
